name: Build SDK (manual)

on:
  workflow_dispatch:
    inputs:
      git_ref:
        description: 'Git ref to build'
        type: string
        default: main
  push:
    branches:
      - main
    paths:
      - 'sdk/**'
      - 'configs/sdk_defconfig'
      - 'buildroot'

permissions:
  contents: read
  packages: write

jobs:
  build:
    if: github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}/ci-buildroot:main

    steps:
      - name: Install Task
        uses: go-task/setup-task@v1

      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.git_ref || github.ref_name }}
          submodules: recursive
          fetch-depth: 0   # fetch full history and tags so git describe works

      - name: Mark workspace as safe for git (necessary for DinD)
        run: |
          git config --global --add safe.directory "${{github.workspace}}"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config --get-all safe.directory

      - name: Restore buildroot toolchain and downloads
        id: buildroot-host-cache-restore
        uses: actions/cache/restore@v3
        with:
          path: |
            buildroot/dl/
            buildroot/output/host/
          key: ${{ runner.os }}-buildroot-host-${{ hashFiles('buildroot/.config') }}

      - name: Load SDK defconfig
        run: task make:sdk_defconfig

      - name: Build SDK (reloads defconfig)
        run: task sdk

      - name: Save buildroot toolchain and downloads
        if: always()
        id: buildroot-host-cache-save
        uses: actions/cache/save@v3
        with:
          path: |
            buildroot/dl/
            buildroot/output/host/
          key: ${{ steps.buildroot-host-cache-restore.outputs.cache-primary-key }}

      - name: Find SDK tarball
        id: find_sdk
        run: |
          SDK_FILE=$(find buildroot/output/images -maxdepth 1 -type f -name '*sdk-buildroot.tar.gz' | head -n1)
          if [ -z "$SDK_FILE" ]; then
            echo "SDK tarball not found"
            exit 1
          fi
          echo "sdk_file=$SDK_FILE" >> "$GITHUB_OUTPUT"

      - name: Get version
        id: version
        run: echo "version=$(git describe --tags --always)" >> $GITHUB_OUTPUT

      - name: Upload SDK artifact
        uses: actions/upload-artifact@v4
        with:
          name: sdk-${{ steps.verison.outputs.verison }}
          path: ${{ steps.find_sdk.outputs.sdk_file }}
